spring:
  config:
    import: optional:env.properties  # Ensure Spring loads environment variables

  datasource:
    url: jdbc:postgresql://postgres_db:5432/kakeibo
    username: kakeibo_user
    password: kakeibo_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  minio:
    endpoint: http://nginx:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: test-bucket

  scheduling:
    enabled: true

server:
  port: 8080