spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kakeibo
    username: kakeibo_user
    password: kakeibo_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: test-bucket

logging:
  level:
    root: INFO
    org.springframework.boot: DEBUG