version: '3.8'

networks:
  minio_network:
    driver: bridge

volumes:
  postgres_data:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:
  nginx_logs:

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: kakeibo
      POSTGRES_USER: kakeibo_user
      POSTGRES_PASSWORD: kakeibo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - minio_network

  minio1:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio1
    command: server --console-address ":9001" http://minio{1...4}/data
    hostname: minio1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "http://127.0.0.1:9001"
      MINIO_SERVER_URL: "http://nginx:9000"
    volumes:
      - minio1-data:/data
    networks:
      - minio_network

  minio2:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio2
    command: server --console-address ":9001" http://minio{1...4}/data
    hostname: minio2
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "http://127.0.0.1:9001"
      MINIO_SERVER_URL: "http://nginx:9000"
    volumes:
      - minio2-data:/data
    networks:
      - minio_network

  minio3:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio3
    command: server --console-address ":9001" http://minio{1...4}/data
    hostname: minio3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "http://127.0.0.1:9001"
      MINIO_SERVER_URL: "http://nginx:9000"
    volumes:
      - minio3-data:/data
    networks:
      - minio_network

  minio4:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio4
    command: server --console-address ":9001" http://minio{1...4}/data
    hostname: minio4
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "http://127.0.0.1:9001"
      MINIO_SERVER_URL: "http://nginx:9000"
    volumes:
      - minio4-data:/data
    networks:
      - minio_network

  minio-init:
    image: quay.io/minio/mc
    container_name: minio-init
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    volumes:
      - ./minio-init.sh:/minio-init.sh
    entrypoint: ["/bin/sh", "/minio-init.sh"]
    networks:
      - minio_network

  nginx:
    image: nginx:1.19.2-alpine
    container_name: minio_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom nginx.conf
      - nginx_logs:/var/log/nginx  # Persist logs
    ports:
      - "9000:9000"  # API Proxy
      - "9001:9001"  # MinIO Console
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - minio_network

  kakeibo-bills-parser:
    build: .
    container_name: kakeibo-bills-parser
    restart: always
    depends_on:
      - postgres
      - minio1
      - minio2
      - minio3
      - minio4
    environment:
      SPRING_CONFIG_IMPORT: optional:env.properties
      # Ensure the app runs MinIO checks every 20 minutes between 08:00-23:00 GMT+3
      SCHEDULE_CRON: "0 0/20 8-23 * * ?"

    ports:
      - "8080:8080"
    networks:
      - minio_network