CREATE TABLE IF NOT EXISTS bills_metadata (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    counterparty VARCHAR(255) NOT NULL,
    period DATE NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    filename VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);