CREATE TABLE IF NOT EXISTS bills (
    id SERIAL PRIMARY KEY,
    counterparty VARCHAR(255) NOT NULL,
    period DATE NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);